
export enum SearchActionTypes {
    SAERCHBOX_CHANGE = 'SAERCHBOX_CHANGE',

    SAERCH_CHANGE = 'SAERCH_CHANGE',

    FETCH_START = 'FETCH_SEARCH_START',
    FETCH_SUCCESS = 'FETCH_SEARCH_SUCCESS',
    FETCH_FAILED = 'FETCH_SEARCH_FAILED',
    FETCH_PAGE = 'FETCH_PAGE',

    SEARCH_INCREMENT_PAGE = 'SEARCH_INCREMENT_PAGE',
    SAERCH_FILTER_CHANGED = 'SAERCH_FILTER_CHANGED',
    CHANGE_OCCUPANCY = 'CHANGE_OCCUPANCY',
    CHANGE_LOCATION = 'CHANGE_LOCATION',
    CHANGE_STAY = 'CHANGE_STAY'
}